refactor: change deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -40,57 +40,54 @@ jobs:
           echo "Running migrations..."
           dotnet tool restore
           dotnet ef database update --project Comex.API/ComexAPI.csproj --context ProdutoContext --connection "$DATABASE_URL"
-          
+
       - name: Deploy to Render
         env:
-            RENDER_BEARER_TOKEN: ${{ secrets.RENDER_API_KEY }}
-            RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
+          RENDER_BEARER_TOKEN: ${{ secrets.RENDER_API_KEY }}
+          RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
         run: |
-            RESPONSE=$(curl -X POST https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/deploys \
-              -H "Authorization: Bearer $RENDER_BEARER_TOKEN" \
-              -H "Content-Type: application/json" \
-              -w "%{http_code}" \
-              -o response.json \
-              -s)
-    
-            if [ "$RESPONSE" -eq 201 ]; then
-              echo "Deploy iniciado com sucesso!"
-              cat response.json
-              DEPLOY_ID=$(jq -r '.id' response.json)
-              
-              echo "DEPLOY_ID=$DEPLOY_ID" >> $GITHUB_ENV  
-            else
-              echo "Falha ao iniciar o deploy. Código de status: $RESPONSE"
-              cat response.json
-              exit 1
-            fi
+          RESPONSE=$(curl -X POST https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/deploys \
+            -H "Authorization: Bearer $RENDER_BEARER_TOKEN" \
+            -H "Content-Type: application/json" \
+            -w "%{http_code}" \
+            -o response.json \
+            -s)
+
+          if [ "$RESPONSE" -eq 201 ]; then
+            echo "Deploy iniciado com sucesso!"
+            cat response.json
+            DEPLOY_ID=$(jq -r '.id' response.json)
+            
+            echo "DEPLOY_ID=$DEPLOY_ID" >> $GITHUB_ENV  
+          else
+            echo "Falha ao iniciar o deploy. CÃ³digo de status: $RESPONSE"
+            cat response.json
+            exit 1
+          fi
 
       - name: Check deploy status
         env:
-            RENDER_BEARER_TOKEN: ${{ secrets.RENDER_API_KEY }}
-            RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
-            DEPLOY_ID: ${{ env.DEPLOY_ID }}
+          RENDER_BEARER_TOKEN: ${{ secrets.RENDER_API_KEY }}
+          RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
+          DEPLOY_ID: ${{ env.DEPLOY_ID }}
         run: |
-            while true; do
-      
-              URL="https://api.render.com/v1/services/$RENDER_SERVICE_ID/deploys/$DEPLOY_ID"
-             
-              RESPONSE=$(curl -X GET \
-                $URL \
-                -H "Authorization: Bearer $RENDER_BEARER_TOKEN" \
-                --header 'Accept: application/json')
+          while true; do
+            URL="https://api.render.com/v1/services/$RENDER_SERVICE_ID/deploys/$DEPLOY_ID"
+           
+            RESPONSE=$(curl -X GET \
+              $URL \
+              -H "Authorization: Bearer $RENDER_BEARER_TOKEN" \
+              --header 'Accept: application/json')
 
-              STATUS=$(echo "$RESPONSE" | jq -r '.status')
-              
-              if [[ "$STATUS" == "live" ]]; then
-                echo "Deploy succeeded!"
-                break
-              elif [[ "$STATUS" == "build_failed" || "$STATUS" == "update_failed" || "$STATUS" == "pre_deploy_failed" ]]; then
-                echo "Deploy failed!"
-                exit 1
-              fi
+            STATUS=$(echo "$RESPONSE" | jq -r '.status')
+            
+            if [[ "$STATUS" == "live" ]]; then
+              echo "Deploy succeeded!"
+              break
+            elif [[ "$STATUS" == "build_failed" || "$STATUS" == "update_failed" || "$STATUS" == "pre_deploy_failed" ]]; then
+              echo "Deploy failed!"
+              exit 1
+            fi
 
-              sleep 60
-            done
-
-
+            sleep 60
+          done
