build: fix status

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -72,19 +72,19 @@ jobs:
                   https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/deploys/$DEPLOY_ID \
                   -H "Authorization: Bearer $RENDER_BEARER_TOKEN")
         
-                STATUS=$(echo $RESPONSE | jq -r '.status')
-                echo "Deploy status: $STATUS"
-        
-                if [[ "$STATUS" == "live" ]]; then
-                  echo "Deploy succeeded!"
-                  break
-                elif [[ "$STATUS" == "build_failed" || "$STATUS" == "update_failed" || "$STATUS" == "pre_deploy_failed" ]]; then
-                  echo "Deploy failed!"
-                  exit 1
-                fi
-        
-                sleep 30
-              done
+                 STATUS=$(echo "$RESPONSE" | jq -r '.status')
+                  echo "Deploy status: $STATUS"
+
+                  if [[ "$STATUS" == "live" ]]; then
+                    echo "Deploy succeeded!"
+                    break
+                  elif [[ "$STATUS" == "build_failed" || "$STATUS" == "update_failed" || "$STATUS" == "pre_deploy_failed" ]]; then
+                    echo "Deploy failed!"
+                    exit 1
+                  fi
+
+                  sleep 30
+                done
 
 
 
