build: set the value of DEPLOYID

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -40,6 +40,7 @@ jobs:
           echo "Running migrations..."
           dotnet tool restore
           dotnet ef database update --project Comex.API/ComexAPI.csproj --context ProdutoContext --connection "$DATABASE_URL"
+          
       - name: Deploy to Render
         env:
             RENDER_BEARER_TOKEN: ${{ secrets.RENDER_API_KEY }}
@@ -58,45 +59,44 @@ jobs:
               DEPLOY_ID=$(jq -r '.id' response.json)
 
               echo "Deploy ID: $DEPLOY_ID"
-              echo "::set-output name=DEPLOY_ID::$DEPLOY_ID"
+              echo "DEPLOY_ID=$DEPLOY_ID" >> $GITHUB_ENV  
             else
               echo "Falha ao iniciar o deploy. Código de status: $RESPONSE"
               cat response.json
               exit 1
             fi
-            outputs:
-             DEPLOY_ID: $DEPLOY_ID
 
       - name: Check deploy status
         env:
-              RENDER_BEARER_TOKEN: ${{ secrets.RENDER_API_KEY }}
-              RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
-              DEPLOY_ID: ${{ steps.deploy.outputs.DEPLOY_ID }}
+            RENDER_BEARER_TOKEN: ${{ secrets.RENDER_API_KEY }}
+            RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
+            DEPLOY_ID: ${{ env.DEPLOY_ID }}
         run: |
-              while true; do
-                 echo "Deploy ID: $DEPLOY_ID"
-                 
-                  URL="https://api.render.com/v1/services/$RENDER_SERVICE_ID/deploys/$DEPLOY_ID"
-                  echo "URL completa: $URL"
+            while true; do
+              echo "Deploy ID: $DEPLOY_ID"
+      
+              URL="https://api.render.com/v1/services/$RENDER_SERVICE_ID/deploys/$DEPLOY_ID"
+              echo "URL completa: $URL"
 
-                RESPONSE=$(curl -X GET \
-                  $URL \
-                  -H "Authorization: Bearer $RENDER_BEARER_TOKEN" \
-                  --header 'Accept: application/json')
+              RESPONSE=$(curl -X GET \
+                $URL \
+                -H "Authorization: Bearer $RENDER_BEARER_TOKEN" \
+                --header 'Accept: application/json')
 
-                 echo "Full response: $RESPONSE" 
+              echo "Full response: $RESPONSE" 
 
-                  STATUS=$(echo "$RESPONSE" | jq -r '.status')
-                  echo "Deploy status: $STATUS"
-  
-                  if [[ "$STATUS" == "live" ]]; then
-                    echo "Deploy succeeded!"
-                    break
-                  elif [[ "$STATUS" == "build_failed" || "$STATUS" == "update_failed" || "$STATUS" == "pre_deploy_failed" ]]; then
-                    echo "Deploy failed!"
-                    exit 1
-                  fi
-  
-                  sleep 30
-                done
+              STATUS=$(echo "$RESPONSE" | jq -r '.status')
+              echo "Deploy status: $STATUS"
+
+              if [[ "$STATUS" == "live" ]]; then
+                echo "Deploy succeeded!"
+                break
+              elif [[ "$STATUS" == "build_failed" || "$STATUS" == "update_failed" || "$STATUS" == "pre_deploy_failed" ]]; then
+                echo "Deploy failed!"
+                exit 1
+              fi
+
+              sleep 30
+            done
+
 
