build: fix url get status

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -63,36 +63,30 @@ jobs:
             fi
       - name: Check deploy status
         env:
-          RENDER_BEARER_TOKEN: ${{ secrets.RENDER_API_KEY }}
-          RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
-          DEPLOY_ID: ${{ steps.deploy.outputs.DEPLOY_ID }}
+              RENDER_BEARER_TOKEN: ${{ secrets.RENDER_API_KEY }}
+              RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
+              DEPLOY_ID: ${{ steps.deploy.outputs.DEPLOY_ID }}
         run: |
-          while true; do
-            RESPONSE=$(curl -X GET \
-              https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/deploys \
-              -H "Authorization: Bearer $RENDER_BEARER_TOKEN")
-            echo "API Response: $RESPONSE"
+              while true; do
+                RESPONSE=$(curl -X GET \
+                  https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/deploys/$DEPLOY_ID \
+                  -H "Authorization: Bearer $RENDER_BEARER_TOKEN")
+                echo "API Response: $RESPONSE"
         
-            DEPLOY=$(echo $RESPONSE | jq -r --arg DEPLOY_ID "$DEPLOY_ID" '.[] | select(.deploy.id == $DEPLOY_ID) | .deploy')
+                STATUS=$(echo $RESPONSE | jq -r '.status')
+                echo "Deploy status: $STATUS"
         
-            if [ -z "$DEPLOY" ]; then
-              echo "Deploy ID not found in response"
-              exit 1
-            fi
+                if [[ "$STATUS" == "live" ]]; then
+                  echo "Deploy succeeded!"
+                  break
+                elif [[ "$STATUS" == "build_failed" || "$STATUS" == "update_failed" || "$STATUS" == "pre_deploy_failed" ]]; then
+                  echo "Deploy failed!"
+                  exit 1
+                fi
         
-            STATUS=$(echo $DEPLOY | jq -r '.status')
-            echo "Deploy status: $STATUS"
-        
-            if [[ "$STATUS" == "live" ]]; then
-              echo "Deploy succeeded!"
-              break
-            elif [[ "$STATUS" == "build_failed" || "$STATUS" == "update_failed" || "$STATUS" == "pre_deploy_failed" ]]; then
-              echo "Deploy failed!"
-              exit 1
-            fi
-        
-            sleep 30
-          done
+                sleep 30
+              done
+
 
 
 
